@startuml

left to right direction

class Category {
  -id: int
  -name: string
  -created_at: timestamp
  -updated_at: timestamp
  -- 
  +courses(): hasMany
}

class Course {
  -id: int
  -title: string
  -description: string
  -category_id: int
  -created_at: timestamp
  -updated_at: timestamp
  -- 
  +category(): belongsTo
  +users(): belongsTo
  +comments(): hasMany
  +favorites(): belongsToMany
  +questions(): hasMany
}

class User {
  -id: int
  -name: string
  -email: string
  -email_verified_at: timestamp
  -password: string
  -created_at: timestamp
  -updated_at: timestamp
  --
  +courses(): hasMany
  +comments(): hasMany
  +favorites(): hasOne
  +questions(): hasMany
}

class Comment {
  -id: int
  -user_id: int
  -course_id: int
  -content: string
  -created_at: timestamp
  -updated_at: timestamp
  --
  +user(): belongsTo
  +course(): belongsTo
}

class Favorite {
  -id: int
  -user_id: int
  -course_id: int
  -created_at: timestamp
  -updated_at: timestamp
  --
  +user(): belongsTo
  +course(): hasMany
}

class Question {
    -id: bigint
    -question_content: text
    -a: string
    -b: string
    -c: string
    -d: string
    -answer: string
    -user_id: int
    -course_id: int
    -created_at: datetime
    -updated_at: datetime
    --
    +user(): belongsTo
    +course(): belongsTo
}

Category "1" --> "*" Course 
User "1" --> "*" Course
Course "1" --> "*" Favorite : "belongsToMany"
Favorite "1" --> "*" Course
Course "1" --> "*" Question
User "1" --> "*" Comment
Course "1" --> "*" Comment
User "1" --> "1" Favorite
User "1" --> "*" Question

@enduml
