@startuml

left to right direction

class Category {
  -id: int
  -name: string
  -created_at: timestamp
  -updated_at: timestamp
  -- 
  +courses(): hasMany
}

class Course {
  -id: int
  -title: string
  -description: string
  -category_id: int
  -created_at: timestamp
  -updated_at: timestamp
  -- 
  +category(): belongsTo
  +users(): belongsTo
  +comments(): hasMany
  +favorites(): hasMany
}

class User {
  -id: int
  -name: string
  -email: string
  -email_verified_at: timestamp
  -password: string
  -created_at: timestamp
  -updated_at: timestamp
  --
  +courses(): hasMany
  +comments(): hasMany
  +favorites(): hasMany
  +questions(): hasMany
}

class Comment {
  -id: int
  -user_id: int
  -course_id: int
  -content: string
  -created_at: timestamp
  -updated_at: timestamp
  --
  +user(): belongsTo
  +course(): belongsTo
}

class Favorite {
  -id: int
  -user_id: int
  -course_id: int
  -created_at: timestamp
  -updated_at: timestamp
  --
  +user(): belongsTo
  +course(): belongsToMany
}

class Question {
    +id: bigint
    +question_content: text
    +a: string
    +b: string
    +c: string
    +d: string
    +answer: string
    +user_id: belongsTo
    +course_id: bigint
    +created_at: datetime
    +updated_at: datetime
}

Category "1" --> "*" Course
Course "*" --> "1" Category
Course "*" --> "*" User
User "1" --> "*" Comment
Course "1" --> "*" Comment
User "1" --> "*" Favorite
Course "1" --> "*" Favorite
User "1" --> "*" Question
Course "1" --> "*" Question
Comment "*" --> "1" User
Comment "*" --> "1" Course
Favorite "*" --> "1" User
Favorite "*" --> "1" Course
Question "*" --> "1" User
Question "*" --> "1" Course

@enduml
