version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_URL: "https://finalproject-production-3eb4.up.railway.app"

      # Database configuration
      DB_CONNECTION: "mysql"
      DB_HOST: "${MYSQLHOST}"
      DB_PORT: "${MYSQLPORT}"
      DB_DATABASE: "${MYSQLDATABASE}"
      DB_USERNAME: "${MYSQLUSER}"
      DB_PASSWORD: "${MYSQLPASSWORD}"

      # Mail configuration
      MAIL_MAILER: "smtp"
      MAIL_HOST: "smtp.gmail.com"
      MAIL_PORT: "587"
      MAIL_USERNAME: "edwardly2023@gmail.com"
      MAIL_PASSWORD: "ymxl xqsh hpeg eszr"
      MAIL_ENCRYPTION: "tls"
      MAIL_FROM_ADDRESS: "edwardly2023@gmail.com"
      MAIL_FROM_NAME: "E-Courses"

      # Pusher configuration
      PUSHER_APP_ID: "1899473"
      PUSHER_APP_KEY: "c731a652cdced3a196d1"
      PUSHER_APP_SECRET: "09f4dd40583959313c2f"
      PUSHER_APP_CLUSTER: "ap1"

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "railway"
      MYSQL_ROOT_PASSWORD: "MGTjSPsxIjNLFpPBsQOzUxIrggRfXYCn"
      MYSQL_USER: "root"
